(DEFPARAMETER *CCG-GRAMMAR*
  '(((KEY 1) (PHON THE) (MORPH D)
     (SYN
      (((BCAT NP) (FEATS NIL)) (DIR FS) (MODAL STAR) ((BCAT N) (FEATS NIL))))
     (SEM (LAM X ("DEF" X))) (PARAM 1.0))
    ((KEY 2) (PHON ARTICLES) (MORPH N) (SYN ((BCAT N) (FEATS NIL)))
     (SEM "ARTICLES") (PARAM 1.0))
    ((KEY 3) (PHON THAT) (MORPH REL)
     (SYN
      ((((BCAT N) (FEATS NIL)) (DIR BS) (MODAL HARMONIC)
        ((BCAT N) (FEATS NIL)))
       (DIR FS) (MODAL HARMONIC)
       (((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (LAM Q (LAM X (("AND" (P X)) (Q X)))))) (PARAM 1.0))
    ((KEY 4) (PHON HARRY) (MORPH N)
     (SYN
      (((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL)
       (((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "HARRY"))) (PARAM 1.0))
    ((KEY 5) (PHON SALLY) (MORPH N)
     (SYN
      (((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL)
       (((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "SALLY"))) (PARAM 1.0))
    ((KEY 6) (PHON MARY) (MORPH N)
     (SYN
      (((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL)
       (((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "MARY"))) (PARAM 1.0))
    ((KEY 7) (PHON MARY) (MORPH N)
     (SYN
      ((((BCAT VP) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR BS) (MODAL ALL)
       ((((BCAT VP) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "MARY"))) (PARAM 1.0))
    ((KEY 8) (PHON MARY) (MORPH N)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR BS) (MODAL ALL)
       ((((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "MARY"))) (PARAM 1.0))
    ((KEY 9) (PHON REJECTED) (MORPH V)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X1 (LAM X2 (("REJECT" X1) X2)))) (PARAM 1.0))
    ((KEY 10) (PHON WITHOUT) (MORPH ADV)
     (SYN
      (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR BS) (MODAL ALL)
        (((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
       (DIR FS) (MODAL ALL) ((BCAT VP) (FEATS NIL))))
     (SEM (LAM P (LAM Q (LAM X (("WOUT" (Q X)) (P X)))))) (PARAM 1.0))
    ((KEY 11) (PHON READING) (MORPH GER)
     (SYN
      (((BCAT VP) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X1 (LAM X2 (("READ" X1) X2)))) (PARAM 1.0))
    ((KEY 12) (PHON SHOWING) (MORPH GER)
     (SYN
      ((((BCAT VP) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X1 (LAM X2 (LAM X3 ((("SHOW" X2) X1) X3))))) (PARAM 1.0))
    ((KEY 13) (PHON GAVE) (MORPH V)
     (SYN
      (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X1 (LAM X2 (LAM X3 ((("GIVE" X1) X2) X3))))) (PARAM 1.0))
    ((KEY 14) (PHON GAVE) (MORPH V)
     (SYN
      (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT PP) (FEATS NIL)))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X1 (LAM X2 (LAM X3 ((("GIVE" X2) X1) X3))))) (PARAM 1.0))
    ((KEY 15) (PHON SHOWED) (MORPH V)
     (SYN
      (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL))))
     (SEM (LAM X1 (LAM X2 (LAM X3 ((("SHOW" X1) X2) X3))))) (PARAM 1.0))
    ((KEY 16) (PHON HARRY) (MORPH N)
     (SYN
      (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR BS) (MODAL ALL)
       (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
         (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "HARRY"))) (PARAM 1.0))
    ((KEY 17) (PHON SALLY) (MORPH N)
     (SYN
      (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR BS) (MODAL ALL)
       (((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
         (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "SALLY"))) (PARAM 1.0))
    ((KEY 18) (PHON BOOKS) (MORPH N)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR BS) (MODAL ALL)
       ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "BOOKS"))) (PARAM 1.0))
    ((KEY 19) (PHON BOOKS) (MORPH N)
     (SYN
      (((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL)
       (((BCAT S) (FEATS NIL)) (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "BOOKS"))) (PARAM 1.0))
    ((KEY 20) (PHON RECORDS) (MORPH N)
     (SYN
      ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
       (DIR BS) (MODAL ALL)
       ((((BCAT S) (FEATS NIL)) (DIR BS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))
        (DIR FS) (MODAL ALL) ((BCAT NP) (FEATS NIL)))))
     (SEM (LAM P (P "RECORDS"))) (PARAM 1.0))
    ((KEY 21) (PHON AND) (MORPH C)
     (SYN
      ((((BCAT @X) (FEATS NIL)) (DIR BS) (MODAL STAR) ((BCAT @X) (FEATS NIL)))
       (DIR FS) (MODAL STAR) ((BCAT @X) (FEATS NIL))))
     (SEM (LAM P (LAM Q (("AND" P) Q)))) (PARAM 1.0))
    ((KEY 22) (PHON AND) (MORPH C)
     (SYN
      ((((BCAT @X) (FEATS NIL)) (DIR BS) (MODAL STAR) ((BCAT @X) (FEATS NIL)))
       (DIR FS) (MODAL STAR) ((BCAT @X) (FEATS NIL))))
     (SEM (LAM P (LAM Q (LAM X (("AND" (P X)) (Q X)))))) (PARAM 1.0))
    ((KEY 23) (PHON AND) (MORPH C)
     (SYN
      ((((BCAT @X) (FEATS NIL)) (DIR BS) (MODAL STAR) ((BCAT @X) (FEATS NIL)))
       (DIR FS) (MODAL STAR) ((BCAT @X) (FEATS NIL))))
     (SEM (LAM P (LAM Q (LAM X (LAM Y (("AND" ((P X) Y)) ((Q X) Y)))))))
     (PARAM 1.0))))